# Generated by Django 5.1.6 on 2025-04-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tarea_aceptada_por_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='puntaje',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
    ]
