# Generated by Django 5.1.6 on 2025-04-25 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tarea_prioridad_alter_calificacion_puntaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='puntuacion',
        ),
    ]
