# Generated by Django 5.1.6 on 2025-04-25 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_calificacion_puntuacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AceptacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aceptacion', models.DateTimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.empleadoperfil')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tarea')),
            ],
        ),
    ]
