# Generated by Django 5.1.6 on 2025-05-20 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_aceptaciontarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordatorios_activos', models.BooleanField(default=True)),
                ('metodo_recordatorios', models.CharField(choices=[('pantalla', 'Mostrar en pantalla'), ('correo', 'Enviar por correo')], default='pantalla', max_length=10)),
                ('tienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='tasks.tienda')),
            ],
        ),
    ]
