# Generated by Django 5.1.6 on 2025-05-21 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tiendaconfiguracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tiempo_estimado', models.DurationField()),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
