# Generated by Django 5.1.6 on 2025-05-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_plantillatarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='puntaje',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
