# Generated by Django 5.1.6 on 2025-05-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_calificacion_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='tiempo_estimado',
            field=models.DurationField(help_text='Formato: HH:MM'),
        ),
    ]
